version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "06:00"
      timezone: "Europe/Zurich"
    open-pull-requests-limit: 3
    groups:
      github-actions:
        patterns:
          - "*"
      github-actions-security:
        applies-to: "security-updates"
        patterns:
          - "*"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "06:15"
      timezone: "Europe/Zurich"
    open-pull-requests-limit: 3
    groups:
      python-routine:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
      python-security:
        applies-to: "security-updates"
        patterns:
          - "*"
